[profile.default]
via_ir = true
optimizer = true
optimizer_runs = 100000
bytecode_hash = "none"
evm_version = "cancun"
dynamic_test_linking = true
remappings = []

[profile.default.fmt]
wrap_comments = true

[profile.no_via_ir]
via_ir = false

[fuzz]
runs = 2048

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
